// Generated by CoffeeScript 1.12.2
(function() {
  var CND, MNEMONIST, badge, debug, echo, help, info, rpr, urge, warn, Σ_missing;

  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'TRIODE';

  debug = CND.get_logger('debug', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  help = CND.get_logger('help', badge);

  warn = CND.get_logger('warn', badge);

  echo = CND.echo.bind(CND);

  MNEMONIST = require('mnemonist');

  Σ_missing = Symbol('missing');

  this["new"] = function() {
    var deleteProperty, get, resolve, set, store, trie;
    trie = new MNEMONIST.Trie();
    store = {};
    resolve = function(prefix) {
      var keys;
      keys = trie.get(prefix);
      if (keys.length === 0) {
        return Σ_missing;
      }
      if (keys.length !== 1) {
        throw new Error("unspecific prefix " + (rpr(prefix)));
      }
      return keys[0];
    };
    set = (function(_this) {
      return function(_, key, value) {
        trie.add(key);
        return store[key] = value;
      };
    })(this);
    get = (function(_this) {
      return function(_, prefix) {
        return store[resolve(prefix)];
      };
    })(this);
    deleteProperty = function(_, prefix) {
      return delete store[resolve(prefix)];
    };
    return new Proxy(store, {
      get: get,
      set: set,
      deleteProperty: deleteProperty
    });
  };

}).call(this);

//# sourceMappingURL=main.js.map
